apiVersion: xlscsde.nhs.uk/v1
kind: SecretsDistribution
metadata:
  name: pat-token
  namespace: ${keda_namespace}
  annotations:
    xlscsde.nhs.uk/secretUsage: "PAT Token"
spec:
  name: pat-token
  type: Opaque
  secrets:
  - from: PatToken
    to: token