apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pat-token-sync
  namespace: keda
  annotations:
    lsc-sde.io/secretUsage: "PAT Token"
spec:
  provider: azure
  secretObjects:
  - secretName: pat-token
    type: Opaque
    data: 
    - objectName: PatToken
      key: token
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ${azure_client_id}
    keyvaultName: ${azure_keyvault_name}
    tenantId: "${azure_tenant_id}"
    objects: |
        array:
        - |
          objectName: PatToken
          objectType: secret