apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pat-token-sync
  annotations:
    lsc-sde.io/secretUsage: "PAT Token"
spec:
  provider: azure
  secretObjects:
  - secretName: pat-token
    type: Opaque
    data: 
    - objectName: PatToken
      key: token
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "009297ad-7a13-4d98-91d0-46f68c815882"
    keyvaultName: lscsdesandbox-kvlt
    tenantId: "f12f0279-8a84-4068-8322-7a6fb0f839b8"
    objects: |
        array:
        - |
          objectName: PatToken
          objectType: secret