apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
  annotations:
    xlscsde.nhs.uk/flux-branch: ${keda_branch}
spec:
  targetNamespace: keda
  releaseName: keda
  chart:
    spec:
      chart: keda
      version: ${keda_chart_version}
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: keda
  interval: 5m0s
  install:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  upgrade:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true